export const shopCardData = [
    {
      id:"34",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"44",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"54",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"64",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"74",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"84",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      total: "TOTAL items -5600",
      id:"94",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"121",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"232",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"334",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"534",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"634",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"734",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"834",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
    {
      id:"934",
      total: "TOTAL items -5600",
      view: "12",
      like: "92",
      coverImgUrl: "marketplace-assets/assets/images/card-banner.png",
      userImgUrl: "marketplace-assets/assets/images/shop-card-user-img.png",
      userName: "@username",
      collected: "45 ITEMS",
      listedForSale: "20 ITEMS",
    },
  
  ]