import Head from "next/head";
import HomeComponent from "../src/components/app/HomeComponent";

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/marketplace/assets/images/favicon.ico" />
      </Head>
      <HomeComponent />
    </div>
  );
}
